### ISSUE TITLE
GuardInjector seems to break @nestjs/passport

### ISSUE THREAD

**Issue by icco** [MetinSeylan/Nestjs-OpenTelemetry#12]
I'm still trying to figure out why, but if you use the GuardInjector w/ @nestjs/passport package, you get an error `this.getAuthenticateOptions is not a function` but if you remove the GuardInjector, everything works fine.

**Comment by aaron-harvey** [comment]
I think the guard is missing a `this.isDecorated` check

I was playing around with the injectors in a stripped down version of this library (trying to trace #13) - it looks like `GuardInjector` is missing the `this.isDecorated` check that controller etc has, and once added, seemed to fix guard classes with instance level methods.

**Comment by MetinSeylan** [comment]
@aaron-harvey you can check pr, the problem is basic js scope :), btw thanks for the feedback issue fixed 👍
