### ISSUE TITLE
question: trace_id span_id

### ISSUE THREAD

**Issue by jek-bao-choo** [MetinSeylan/Nestjs-OpenTelemetry#20]
Hi Metin, is there are a way to inject `{...., trace_id: xxx, span_id: yyy, ....}`  into the log lines?

**Comment by jek-bao-choo** [comment]
Something similar to this code example https://github.com/pragmaticivan/nestjs-otel#using-with-a-logger

**Comment by MetinSeylan** [comment]
hi @jek-bao-choo, by default this library supports nestjs ConsoleLogger injector but you have to implement trace exporter in your module definition. for the 3 party libraries, you can use exact same example code you mention that in the link

**Comment by jek-bao-choo** [comment]
Hi Metin, thank you for your reply. Is this documented?

Appreciate your contribution to the OTel community.
