### ISSUE TITLE
@Counter is registered as @Observer 

### ISSUE THREAD

**Issue by Sceri** [MetinSeylan/Nestjs-OpenTelemetry#26]
The `DecoratorObserverMetricInjector` and `DecoratorCounterMetricInjector` lack checks for decorator type in some places. Because of this `@Counter` functions can register as `@Observer` and export Histogram instead of Counter

The opposite situation is also possible, I think

**Comment by MetinSeylan** [comment]
@Sceri thanks for feedback, #27 merged
