### ISSUE TITLE
Structured Logs and OpenTelemetry trace context

### ISSUE THREAD

**Issue by pragmaticivan** [MetinSeylan/Nestjs-OpenTelemetry#4]
Are there any recommendation for structured logs, hopefully following some key/value patterns from https://w3c.github.io/trace-context/ ?

**Comment by pragmaticivan** [comment]
It appears it can be accomplished by using https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-pino

But I'm not able to make it work. I Will test it a bit more.

**Comment by pragmaticivan** [comment]
I ended up going with that on Pino:

```
formatters: {
    level(label) {
      return { level: label };
    },
    log(object) {
      const span = trace.getSpan(context.active());
      if (!span) return { ...object };
      const { spanId, traceId } = trace.getSpan(context.active())?.spanContext();
      return { ...object, spanId, traceId };
    },
  },
```

**Comment by Djiit** [comment]
Hey, I'm looking for a way to insert traceIds in my Pino logger. How did you use the snippet above ? Thanks
