### ISSUE TITLE
http_request_duration_seconds reports milliseconds

### ISSUE THREAD

**Issue by Informatic** [MetinSeylan/Nestjs-OpenTelemetry#40]
Hey!
This produces values in milliseconds:
https://github.com/MetinSeylan/Nestjs-OpenTelemetry/blob/main/src/Metric/Interceptors/Http/MetricHttpEventProducer.ts#L20-L21

Besides wrong metric name, default buckets configuration (`[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10]`) also makes this metric unusable.

I think seconds is a commonly accepted unit for request duration histograms, so that value should probably be adjusted accordingly.

**Comment by MetinSeylan** [comment]
#49
