### ISSUE TITLE
This library is missing from Open Telemetry registry

### ISSUE THREAD

**Issue by jtmalinowski** [MetinSeylan/Nestjs-OpenTelemetry#7]
Hi @MetinSeylan,
I'm opening this issue just to let you know that I'm adding this library to the registry in this PR: <https://github.com/open-telemetry/opentelemetry.io/pull/626>. If you'd prefer that `Nestjs-OpenTelemetry` wasn't in the registry, let me know, otherwise thank you for taking the time to create this library.

**Comment by jtmalinowski** [comment]
I have a couple thoughts after reviewing the code:
- I think this library would benefit from clearly dividing the instrumentation part (i.e. creating spans, context management, trace id injection in logs) and Nest helpers (services, initialization, etc.)
- in other words, that division would best be done by exporting a `NestInstrumentation`, which you can use when initialising Open Telemetry
- it's not immediately clear if spans will be created for actions/handlers without `@Span` annotation, it looks to me like they won't, which is a bit unusual for an instrumentation of this kind
- the purpose of [TraceInterceptor](https://github.com/MetinSeylan/Nestjs-OpenTelemetry/blob/main/src/Tracing/TraceInterceptor.ts) is a bit unclear, did OTel propagators not work for you otherwise?

If you think you have the right Nest expertise to drive the design on Nest's end of this library, I can check if @splunk would commit some resources to make this library play a bit more nicely with Open Telemetry - good support for instrumentation in Nest is on our list.

**Comment by mentos1386** [comment]
@jtmalinowski i think you might be interested in https://github.com/pragmaticivan/nestjs-otel.

**Comment by jtmalinowski** [comment]
@mentos1386 thanks for the tip. The repo you linked only provides metrics and some manual instrumentation helpers. Once metrics specification matures, it will be nice to incorporate it.

**Comment by jtmalinowski** [comment]
@MetinSeylan I'm closing for now, this library is now in the registry. Maybe there'll be a potential for some more collaboration in the future.

**Comment by MetinSeylan** [comment]
@jtmalinowski @mentos1386 we are using this library as a internal tool in my company, that's why we are decided refactor this library dramatically, we are working on it with my team, we will release new version soon, btw thanks for feedback it's important for us

**Comment by jtmalinowski** [comment]
Gotcha.

**Comment by MetinSeylan** [comment]
finally refactored :)
